# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""
English documentation build configuration for Triton Ascend.

Sphinx reads Chinese Markdown from docs/zh/ and applies gettext translations
from locale/en/LC_MESSAGES/ to produce English HTML output.
"""

import os as _os
import sys as _sys

_HERE = _os.path.dirname(__file__)

# ── Project info ──
project = 'Triton Ascend'
copyright = '2025, Huawei'
author = 'Huawei'
version = ''
release = ''

# ── Extensions ──
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
    'myst_parser',
]

autosummary_generate = True

# ── Paths ──
# Source directory is docs/zh/ (the Chinese .md files)
srcdir = _os.path.abspath(_os.path.join(_HERE, "zh"))
_REPO = _os.path.abspath(_HERE)

templates_path = [_os.path.join(srcdir, '_templates')]
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# ── Language & i18n ──
language = 'en'

# Point to the locale directory (relative to srcdir = docs/zh/)
# locale/en/LC_MESSAGES/ contains the .po files generated by translate_md.py
locale_dirs = ['../locale/']
gettext_compact = False
# Extract code blocks (literal blocks) as translatable units so that Chinese
# comments inside code blocks are also translated (not skipped).
gettext_additional_targets = ['literal-block', 'raw', 'image']

# ── Theme ──
pygments_style = 'sphinx'
html_theme = "sphinx_rtd_theme"
html_theme_options = {}
html_static_path = [_os.path.join(srcdir, '_static')]
html_css_files = ["custom.css"]

# ── Mock stubs for triton C extensions ──
_sys.path.insert(0, _os.path.join(_REPO, "python"))


def _load_module(module_name, file_path):
    import importlib.util as _ilu
    spec = _ilu.spec_from_file_location(module_name, file_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {module_name!r} from {file_path!r}")
    module = _ilu.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_force_mock = (_os.environ.get("TRITON_DOCS_FORCE_MOCK", "").lower() in ("1", "true", "yes")
               or _os.environ.get("READTHEDOCS") == "True")
if not _force_mock:
    try:
        import triton  # noqa: F401,E402
    except Exception as _exc:
        print(f"import triton failed ({_exc!r}); building docs with mock stubs")
        _force_mock = True

if _force_mock:
    _mock_path = _os.path.join(srcdir, "_mock", "_triton_mock.py")
    _load_module("docs.zh._mock._triton_mock", _mock_path).install()

import triton  # noqa: E402
import triton.language.extra as _tl_extra  # noqa: E402

_cann_lang_path = _os.path.join(_REPO, "third_party", "ascend", "language")
if _cann_lang_path not in _tl_extra.__path__:
    _tl_extra.__path__.append(_cann_lang_path)

import sphinx.ext.autosummary  # noqa: E402
import sphinx.util.inspect  # noqa: E402


def _unwrap_jit(fn):

    def wrapper(obj, **kwargs):
        if isinstance(obj, triton.runtime.JITFunction):
            obj = obj.fn
        return fn(obj, **kwargs)

    return wrapper


if hasattr(sphinx.ext.autosummary, "get_documenter"):
    _orig_get_documenter = sphinx.ext.autosummary.get_documenter

    def _get_documenter(app, obj, parent):
        if isinstance(obj, triton.runtime.JITFunction):
            obj = obj.fn
        return _orig_get_documenter(app, obj, parent)

    sphinx.ext.autosummary.get_documenter = _get_documenter

sphinx.util.inspect.unwrap_all = _unwrap_jit(sphinx.util.inspect.unwrap_all)
sphinx.util.inspect.signature = _unwrap_jit(sphinx.util.inspect.signature)
sphinx.util.inspect.object_description = _unwrap_jit(sphinx.util.inspect.object_description)


def setup(app):
    _load_module(
        "docs.zh.python_api._inject_ascend_notes",
        _os.path.join(srcdir, "python-api", "_inject_ascend_notes.py"),
    ).setup(app)
