name: Integration Tests NPU

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  integration-tests-ascend:
    name: integration-tests-ascend (${{ matrix.config.name }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.config.runs_on }}
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/triton/triton:dev-4258273a-A3
    timeout-minutes: 300
    strategy:
      matrix:
        config: ${{ fromJson(inputs.matrix) }}
        python-version: ['3.9', '3.10', '3.11']
    env:
      RUNNER_TYPE: ${{ matrix.config.runner_type }}
      TRITON_BUILD_WITH_CCACHE: "true"
      TRITON_BUILD_WITH_CLANG_LLD: "TRUE"
      TRITON_USE_ASSERT_ENABLED_LLVM: "TRUE"
      TRITON_DISABLE_LINE_INFO: 1
      PROTON_SKIP_PC_SAMPLING_TEST: 1
      PYTHON: "python${{ matrix.python-version }}"
      CCACHE_COMPRESS: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"
      - name: Add git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install OS prerequisites
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends \
                ca-certificates ninja-build libzstd-dev \
            git zlib1g-dev \
                clang clang-15 lld-15 ccache
          ${PYTHON} -m pip install cmake ninja -qq
      - name: Compute cache keys
        id: cache-key
        run: |
          llvm_file="cmake/llvm-hash.txt"
          req_file="requirements_dev.txt"
          json_file="cmake/json-version.txt"

          # Check if files exist before proceeding
          if [[ ! -f "$llvm_file" || ! -f "$req_file" || ! -f "$json_file" ]]; then
            echo "Error: Required dependency files are missing."
            exit 1
          fi

          # Process the files if they exist
          echo "llvm=$(cat $llvm_file | cut -c 1-8)" >> $GITHUB_OUTPUT
          echo "req=$(sha256sum $req_file | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
          echo "json=$(cat $json_file)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          # Note that we cannot use environment variables here given there is
          # no shell to interpret them in the paths.
          path: |
            ~/.triton/llvm
            ~/.triton/json
          key: ${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}-llvm-${{ steps.cache-key.outputs.llvm }}-req-${{ steps.cache-key.outputs.req }}-json-${{ steps.cache-key.outputs.json }}
      - name: Inspect cache directories
        run: |
          mkdir -p ~/.triton
          du -h -d 1 ~/.triton

          mkdir -p ~/.ccache
          du -h -d 1 ~/.ccache
      - name: Update PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Setup Python environment
        run: |
          echo "/venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=/venv" >> $GITHUB_ENV
          echo "PYTHONHOME=" >> $GITHUB_ENV
      - name: Build and install triton-ascend
        shell: bash
        run: |
          nproc
          source /usr/local/Ascend/cann/set_env.sh
          npu-smi info
          if [ -n "${ASCEND_TOOLKIT_HOME}" ] && [ -f "${ASCEND_TOOLKIT_HOME}/toolkit/version.info" ]; then
            cat "${ASCEND_TOOLKIT_HOME}/toolkit/version.info"
          fi
          echo "PATH is '$PATH'"
          ccache --zero-stats
          ${PYTHON} -m pip install -r requirements_dev.txt -qq
          NUM_PROCS=$(( $(nproc) / 3 ))
          if [ "$NUM_PROCS" -lt 1 ]; then NUM_PROCS=1; fi
          cd python
          TRITON_BUILD_WITH_CLANG_LLD=true \
          TRITON_BUILD_PROTON=OFF \
          TRITON_WHEEL_NAME="triton-ascend" \
          TRITON_APPEND_CMAKE_ARGS="-DTRITON_BUILD_UT=OFF" \
          MAX_JOBS="$NUM_PROCS" \
          IS_MANYLINUX="${IS_MANYLINUX:-False}" \
          TRITON_WHEEL_VERSION_SUFFIX="${TRITON_WHEEL_VERSION_SUFFIX:-rc3}" \
          ${PYTHON} setup.py bdist_wheel
          cd -
          ${PYTHON} -m pip install python/dist/*.whl -qq
      - name: Install NPU test dependencies
        run: |
          ${PYTHON} -m pip install attrs==24.2.0 numpy==1.26.4 scipy==1.13.1 decorator==5.1.1 psutil==6.0.0 pytest==8.3.2 pytest-xdist==3.6.1 pyyaml mindspore -i https://pypi.tuna.tsinghua.edu.cn/simple
          ${PYTHON} -m pip install torch==2.7.1 torch_npu==2.7.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: CCache Stats
        run: ccache --print-stats
      - name: Run unit tests on NPU
        continue-on-error: true
        shell: bash
        run: |
          source /usr/local/Ascend/cann/set_env.sh
          NUM_PROCS=$(( $(nproc) / 3 ))
          if [ "$NUM_PROCS" -lt 1 ]; then NUM_PROCS=1; fi
          ${PYTHON} -m pytest -s -v -n "$NUM_PROCS" --dist=loadfile third_party/ascend/unittest/pytest_ut
          ${PYTHON} -m pytest -s -v -n "$NUM_PROCS" --dist=loadfile third_party/ascend/unittest/autotune_ut
          ${PYTHON} -m pytest -s -v -n "$NUM_PROCS" --dist=loadfile third_party/ascend/unittest/kernels/test_triton_kernel.py
      - name: Run generalization tests on NPU
        continue-on-error: true
        shell: bash
        run: |
          source /usr/local/Ascend/cann/set_env.sh
          NUM_PROCS=$(( $(nproc) / 3 ))
          if [ "$NUM_PROCS" -lt 1 ]; then NUM_PROCS=1; fi
          ${PYTHON} -m pytest -s -v -n "$NUM_PROCS" --dist=load third_party/ascend/unittest/generalization_cases
      - name: Inspect cache directories
        run: |
          mkdir -p ~/.triton
          du -h -d 1 ~/.triton

          mkdir -p ~/.ccache
          du -h -d 1 ~/.ccache
