name: Wheels

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * *"

permissions: read-all

jobs:
  Build-Wheels:
    timeout-minutes: 180
    runs-on: ${{ matrix.config.runs_on }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {runs_on: 'ubuntu-22.04', arch: 'amd64'}
        - {runs_on: 'ubuntu-22.04-arm', arch: 'arm64'}
        python-version: ['3.9', '3.10', '3.11']

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Build wheels
        run: |
          python --version
          python -m pip install -r requirements_dev.txt -qq
          NUM_PROCS=$(( $(nproc) / 3 ))
          if [ "$NUM_PROCS" -lt 1 ]; then NUM_PROCS=1; fi
          cd python
          TRITON_BUILD_WITH_CLANG_LLD=true \
          TRITON_BUILD_PROTON=OFF \
          TRITON_WHEEL_NAME="triton-ascend" \
          TRITON_APPEND_CMAKE_ARGS="-DTRITON_BUILD_UT=OFF" \
          MAX_JOBS="$NUM_PROCS" \
          IS_MANYLINUX="${IS_MANYLINUX:-False}" \
          TRITON_WHEEL_VERSION_SUFFIX="${TRITON_WHEEL_VERSION_SUFFIX:-rc3}" \
          python setup.py bdist_wheel
          cd -

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-manylinux_2_28_${{ matrix.config.arch }}-py${{ matrix.python-version }}-wheels-upload
          path: python/dist/*.whl

      - name: Upload wheels to OBS
        shell: bash
        env:
          AK: ${{ secrets.OBS_AK }}
          SK: ${{ secrets.OBS_SK }}
        run: |
          if [ -z "${AK}" ] || [ -z "${SK}" ]; then
            echo "Please set OBS_AK and OBS_SK secrets before uploading."
            exit 1
          fi


          OBSUTIL_URL="https://obs-community-intl.obs.ap-southeast-1.myhuaweicloud.com/obsutil/current/obsutil_linux_${{ matrix.config.arch }}.tar.gz"

          curl -fL "$OBSUTIL_URL" -o obsutil.tar.gz

          file obsutil.tar.gz | grep -q gzip || {
            echo "obsutil.tar.gz is not a gzip file"
            exit 1
          }

          tar xzf obsutil.tar.gz
          rm -f obsutil.tar.gz
          mv obsutil* obsutil

          obsutil/obsutil config -i="${AK}" -k="${SK}" -e=https://obs.cn-north-4.myhuaweicloud.com

          obsutil/obsutil cp -u python/dist/*.whl obs://triton-build-package-test/triton-ascend/
