# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
"""
Inject mock stubs for triton C extensions so Sphinx can import triton
source without compiling the native extension (e.g. in CI/doc builds
where CANN is unavailable).

Usage – call ``install()`` before any ``import triton`` statement:

    from docs.zh._mock._triton_mock import install as _install_mock
    _install_mock()
    import triton  # works without compiled _C extensions
"""
import importlib.machinery
import os
import sys
import types
from abc import ABCMeta, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Union
from unittest.mock import MagicMock

# ---------------------------------------------------------------------------
# Minimal stubs for triton.backends.compiler / driver classes
# (keeping them as real Python classes avoids isinstance issues in autodoc)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _GPUTarget:
    backend: str
    arch: Union[int, str]
    warp_size: int


class _Language(Enum):
    TRITON = 0
    GLUON = 1


class _BaseBackend(metaclass=ABCMeta):

    def __init__(self, target) -> None:
        self.target = target

    @staticmethod
    @abstractmethod
    def supports_target(target):
        raise NotImplementedError


class _DriverBase(metaclass=ABCMeta):

    @classmethod
    @abstractmethod
    def is_active(cls):
        raise NotImplementedError

    @abstractmethod
    def get_current_target(self):
        raise NotImplementedError

    @abstractmethod
    def get_active_torch_device(self):
        raise NotImplementedError

    @abstractmethod
    def map_python_to_cpp_type(self, ty: str) -> str:
        raise NotImplementedError

    @abstractmethod
    def get_benchmarker(self):
        raise NotImplementedError


class _AutoModule(types.ModuleType):
    """A module that auto-generates MagicMock for any undefined attribute."""

    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        mock = MagicMock(name=f"{self.__name__}.{name}")
        setattr(self, name, mock)
        return mock


def _make_module(name: str, parent=None) -> types.ModuleType:
    mod = _AutoModule(name)
    mod.__package__ = name
    mod.__path__ = []
    # A real (non-None) spec keeps importlib.util.find_spec(name) working for
    # third-party code probing optional triton submodules.
    mod.__spec__ = importlib.machinery.ModuleSpec(name, loader=None, is_package=True)
    sys.modules[name] = mod
    if parent is not None:
        setattr(parent, name.rsplit(".", 1)[-1], mod)
    return mod


def install() -> None:
    """Populate sys.modules with lightweight stubs for all C extensions."""
    if getattr(sys.modules.get("triton._C"), "__triton_doc_mock__", False):
        return  # our stubs are already installed

    # A failed real `import triton` leaves partially-initialized triton
    # modules behind (e.g. a genuine triton._C without CANN backends); purge
    # them so the stubs and the re-import start from a clean slate.
    for _name in [n for n in sys.modules if n == "triton" or n.startswith("triton.")]:
        del sys.modules[_name]

    # ------------------------------------------------------------------ #
    # triton._C.libtriton  (must come first – imported at triton load)    #
    # ------------------------------------------------------------------ #
    _c = _make_module("triton._C")
    _c.__triton_doc_mock__ = True

    libtriton = _make_module("triton._C.libtriton", parent=_c)
    libtriton.getenv = lambda key, default="": os.environ.get(key, default)
    libtriton.getenv_bool = (lambda key, default=False: os.environ.get(key, "1" if default else "0").lower() in
                             ("1", "true", "yes"))
    libtriton.get_cache_invalidating_env_vars = lambda: []

    # The following symbols are auto-generated by _AutoModule.__getattr__
    # when accessed — kept as comments for discoverability:
    #   libtriton.buffer_ir
    #   libtriton.native_specialize_impl

    # triton._C.libtriton.ascend and triton._C.libtriton.ir — use proper
    # enum stubs so that constants like ir.PROPAGATE_NAN render cleanly in
    # autodoc signatures instead of showing MagicMock repr strings.
    import importlib.util as _ilu
    _mock_dir = os.path.dirname(os.path.abspath(__file__))

    _ir_stub_spec = _ilu.spec_from_file_location(
        "_ir_stub",
        os.path.join(_mock_dir, "_ir_stub.py"),
    )
    _ir_stub = _ilu.module_from_spec(_ir_stub_spec)
    _ir_stub_spec.loader.exec_module(_ir_stub)
    libtriton.ir = _ir_stub

    _stub_spec = _ilu.spec_from_file_location(
        "_ascend_ir_stub",
        os.path.join(_mock_dir, "_ascend_ir_stub.py"),
    )
    _ascend_ir_stub = _ilu.module_from_spec(_stub_spec)
    _stub_spec.loader.exec_module(_ascend_ir_stub)

    ascend_ext = _make_module("triton._C.libtriton.ascend", parent=libtriton)
    ascend_ext.ir = _ascend_ir_stub

    # triton._C.libtriton.gluon_ir / linear_layout (auto-mocked by _AutoModule)
    _make_module("triton._C.libtriton.gluon_ir", parent=libtriton)
    _make_module("triton._C.libtriton.linear_layout", parent=libtriton)

    # ------------------------------------------------------------------ #
    # triton.backends – stub out the whole package so that               #
    # _discover_backends() is never called (it would try to load gpu      #
    # backends registered by a system-wide triton install).               #
    # ------------------------------------------------------------------ #
    _bk_compiler_mod = _make_module("triton.backends.compiler")
    _bk_compiler_mod.GPUTarget = _GPUTarget
    _bk_compiler_mod.Language = _Language
    _bk_compiler_mod.BaseBackend = _BaseBackend

    _bk_driver_mod = _make_module("triton.backends.driver")
    _bk_driver_mod.DriverBase = _DriverBase

    _bk = _make_module("triton.backends")
    _bk.backends = {}
    _bk.BaseBackend = _BaseBackend
    _bk.DriverBase = _DriverBase
    _bk.compiler = _bk_compiler_mod
    _bk.driver = _bk_driver_mod

    # ------------------------------------------------------------------ #
    # triton.backends.ascend  (CANN backend plugin — auto-mocked)          #
    # ------------------------------------------------------------------ #
    for _name in [
            "triton.backends.ascend",
            "triton.backends.ascend.driver",
            "triton.backends.ascend.utils",
            "triton.backends.ascend.compiler",
            "triton.backends.ascend.backend_register",
            "triton.backends.ascend.cpu_driver",
    ]:
        _make_module(_name)

    _make_module("triton.extension")
    _make_module("triton.extension.buffer")

    # ------------------------------------------------------------------ #
    # triton.extension.buffer.language — populated from real source       #
    # via AST parsing so docstrings / signatures stay in sync without     #
    # requiring a working ``import triton`` (no NPU needed).              #
    # ------------------------------------------------------------------ #
    _repo_root = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
    _parse_source_path = os.path.join(_repo_root, "docs", "zh", "python-api", "_parse_source.py")
    _parse_spec = _ilu.spec_from_file_location("_parse_source", _parse_source_path)
    _parse_source = _ilu.module_from_spec(_parse_spec)
    _parse_spec.loader.exec_module(_parse_source)

    _bl_source = os.path.join(_repo_root, "python", "triton", "extension", "buffer", "language", "core.py")
    _parse_source.install_source_module(
        [_bl_source],
        "triton.extension.buffer.language",
        export_filter=[
            "address_space",
            "buffer_type",
            "buffer",
            "alloc",
            "to_buffer",
            "to_tensor",
            "subview",
        ],
    )

    # ------------------------------------------------------------------ #
    # triton.language.extra                                                #
    # ------------------------------------------------------------------ #
    _extra = _make_module("triton.language.extra")
    _cann = _make_module("triton.language.extra.cann", parent=_extra)
    _make_module("triton.language.extra.extension", parent=_extra)

    _cann_src = os.path.join(_repo_root, "third_party", "ascend", "language", "cann")

    # --- triton.language.extra.cann.libdevice ---
    _parse_source.install_source_module(
        [os.path.join(_cann_src, "libdevice.py")],
        "triton.language.extra.cann.libdevice",
    )

    # --- triton.language.extra.cann.extension ---
    _ext_dir = os.path.join(_cann_src, "extension")
    _ext_sources = [
        os.path.join(_ext_dir, f)
        for f in ["core.py", "scope.py", "custom_op.py", "math_ops.py", "aux_ops.py", "vec_ops.py", "mem_ops.py"]
    ]
    _parse_source.install_source_module(
        _ext_sources,
        "triton.language.extra.cann.extension",
    )

    # Add MLIR affine type stubs (C extension bindings; not in .py sources)
    _cann_ext = sys.modules["triton.language.extra.cann.extension"]
    _MLIR_STUBS = [
        "affine_expr",
        "affine_constant_expr",
        "affine_dim_expr",
        "affine_symbol_expr",
        "affine_binary_op_expr",
        "affine_map",
    ]
    for _name in _MLIR_STUBS:
        if not hasattr(_cann_ext, _name):
            _stub_cls = type(_name, (), {"__doc__": f"MLIR {_name} type."})
            setattr(_cann_ext, _name, _stub_cls)

    # ------------------------------------------------------------------ #
    # Optional runtime deps                                               #
    # ------------------------------------------------------------------ #
    try:
        import pybind11  # noqa: F401
    except ImportError:
        sys.modules["pybind11"] = MagicMock(name="pybind11")

    try:
        import torch  # noqa: F401
    except ImportError:
        sys.modules["torch"] = MagicMock(name="torch")
        sys.modules["torch.nn"] = MagicMock(name="torch.nn")
        sys.modules["torch._C"] = MagicMock(name="torch._C")
